site_name: Community operators
repo_name: community-operators
repo_url: https://github.com/redhat-openshift-ecosystem/community-operators-prod
nav:
  - "Overview": README.md
  - "Packaging your Operator for OperatorHub":
      - "Operator structure": packaging-operator.md
      - "Required fields": packaging-required-fields.md
  - "Contributing":
      - "Prerequisites": contributing-prerequisites.md
      - "Where to place operator": contributing-where-to.md
      - "Creating pull request (PR)": contributing-via-pr.md
      - "Operator Publishing / Review settings": operator-ci-yaml.md
      - "OKD/OpenShift Catalogs criteria and options": packaging-required-criteria-ocp.md
  - "Operator pipeline": community-operator-pipeline.md
  - "Best practices": best-practices.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate

plugins:
  - search
