apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: codeflare
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: codeflare-operator-clusterrole-edit
rules:
- apiGroups:
  - workload.codeflare.dev
  resources:
  - schedulingspecs
  - appwrappers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
